version: '3'

services:
  scheduler:
    build: ./Scheduler
    image: abianik/scheduler
    container_name: scheduler
    ports:
      - 8000:8000
    environment:
      - KAFKA_SERVER=192.168.1.4:9092
      - WORKER_PROCESS_COUNT=5
      - SM_MINIUMUM_DELAY=60
      - SM_MAXIUMUM_DELAY=1500
      - SM_BUCKETS_MULTIPLICATION_RATIO=3
      - SM_PARTITIONS_PER_BUCKET=16
      - SM_TOPIC_PARTITIONS=16
  
  messagehandler:
    build: ./MessageHandler
    image: abianik/messagehandler
    container_name: messagehandler
    environment:
      - SCHEDULER_SERVER_URL=http://scheduler:8000
    depends_on:
      - scheduler
  
  worker:
    build: ./Worker
    image: abianik/worker
    container_name: worker
    environment:
      - SCHEDULER_SERVER_URL=http://scheduler:8000
    depends_on:
      - scheduler

networks: 
  default: 
    external: 
      name: kafka-network