version: '3'

services:
  scheduler:
    build: ./Scheduler
    image: abianik/scheduler
    container_name: scheduler
    ports:
      - 8000:8000
    environment:
      - KAFKA_SERVER=kafka:9092
      - WORKER_PROCESS_COUNT=1
  
  messagehandler:
    build: ./MessageHandler
    image: abianik/messagehandler
    container_name: messagehandler
    environment:
      - SCHEDULER_SERVER_URL=http://scheduler:8000
    depends_on:
      - scheduler
  
  worker:
    build: ./Worker
    image: abianik/worker
    environment:
      - SCHEDULER_SERVER_URL=http://scheduler:8000
    depends_on:
      - scheduler
    scale: 4

networks: 
  default: 
    external: 
      name: kafka-network