version: '3'

services:
  messagehandler:
    build: ./MessageHandler
    image: abianik/messagehandler
    volumes: 
      - ./MessageHandler:/app
    environment:
      - SCHEDULER_SERVER_URL=http://scheduler:8000
  
  scheduler:
    build: ./Scheduler
    image: abianik/scheduler
    volumes: 
      - ./Scheduler:/app
    ports:
      - 8000:8000
    environment:
      - KAFKA_SERVER=192.168.28.46:9092