version: '3'

services:
  messagehandler:
    build: ./MessageHandler
    image: abianik/messagehandler
    volumes: 
      - ./MessageHandler:/app
    environment:
      - KAFKA_SERVER=192.168.28.46:9092