version: '3'

services:
  messenger:
    build: ./messenger
    image: abianik/messenger
    container_name: messenger
    environment:
      - KAFKA_SERVER=kafka:9092
      - EXPERIMENT_DURATION_HOURS=0.1
      - EXPERIMENT_MESSAGE_COUNT=10000
      - MESSAGE_SIZE_BYTES=10
      - MESSENGER_SCHEDULER_FREQ=45
      - MESSAGE_DATABASE_URL=mongodb://admin:kafka@mongo:27017/
      - DATABASE_SCHEDULER_HOST=mysql
      - MESSAGE_DATABASE_ENABLED=True
      - DATABASE_SCHEDULER_ENABLED=True
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: kafka

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: kafka
      ME_CONFIG_MONGODB_URL: mongodb://admin:kafka@mongo:27017/
    depends_on:
      - mongo

networks:
  default:
    external:
      name: kafka-network