version: '3'

services:
  database-scheduler:
    image: abianik/database-scheduler
    build: ./database-scheduler
    container_name: database-scheduler
    environment:
      - EXPERIMENT_DURATION_HOURS=${EXPERIMENT_DURATION_HOURS:-0.1}
      - EXPERIMENT_MESSAGE_COUNT=${EXPERIMENT_MESSAGE_COUNT:-10000}
      - MESSAGE_SIZE_BYTES=${MESSAGE_SIZE_BYTES:-100}
      - DATABASE_SCHEDULER_CASSANDRA_ENABLED=${DATABASE_SCHEDULER_CASSANDRA_ENABLED:-True}
      - DATABASE_SCHEDULER_CASSANDRA_HOST=cassandra
      - DATABASE_SCHEDULER_MYSQL_ENABLED=${DATABASE_SCHEDULER_MYSQL_ENABLED:-True}
      - DATABASE_SCHEDULER_MYSQL_HOST=mysql
    restart: unless-stopped
    depends_on:
      - cassandra

  cassandra:
    image: cassandra:4.0.4
    container_name: cassandra
    restart: unless-stopped
    ports:
      - 9042:9042
  
  cassandra-web:
    image: ipushc/cassandra-web
    container_name: cassandra-web
    restart: unless-stopped
    depends_on:
      - cassandra
    environment:
      - CASSANDRA_HOST=cassandra
    links:
      - cassandra
    ports:
      - 8090:8083
  
  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: kafka
      MYSQL_DATABASE: messages
      MYSQL_USER: admin
      MYSQL_PASSWORD: kafka
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8091:8080

networks:
  default:
    external:
      name: kafka-network