version: '3'

services:
  database-scheduler:
    image: abianik/database-scheduler
    build: ./database-scheduler
    container_name: database-scheduler
    environment:
     - MESSAGE_SIZE_BYTES=100
     - DATABASE_SCHEDULER_HOST=cassandra
    restart: unless-stopped
    depends_on:
      - cassandra

  cassandra:
    image: cassandra:4.0.4
    container_name: cassandra
    restart: unless-stopped
    ports:
      - 9042:9042
  
  cassandra-web:
    image: ipushc/cassandra-web
    container_name: cassandra-web
    restart: unless-stopped
    depends_on:
      - cassandra
    environment:
      - CASSANDRA_HOST=cassandra
    links:
      - cassandra
    ports:
      - 8090:8083

networks:
  default:
    external:
      name: kafka-network