version: '3'
services:
  docker-monitor:
    container_name: docker-monitor
    image: abianik/docker-monitor
    build: ./docker-monitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker-monitor:/app
    environment:
      - DOCKER_MONITOR_INTERVAL=${DOCKER_MONITOR_INTERVAL:-30}
      - KAFKA_ENABLED=${KAFKA_ENABLED:-True}
      - KAFKA_SCHEDULER_SERVER_URL=http://scheduler:8000
      - DATABASE_SCHEDULER_CASSANDRA_ENABLED=${DATABASE_SCHEDULER_CASSANDRA_ENABLED:-True}
      - DATABASE_SCHEDULER_MYSQL_ENABLED=${DATABASE_SCHEDULER_MYSQL_ENABLED:-True}

  kafka-jmx-exporter:
    image: bitnami/jmx-exporter:latest
    container_name: kafka-jmx-exporter
    ports:
      - 5556:5556
    volumes:
     - ./kafka-jmx-exporter.yml:/opt/bitnami/jmx-exporter/config.yml
    command: 5556 config.yml
    restart: unless-stopped

  prometheus:
    image: "prom/prometheus:latest"
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
     - ./prometheus:/prometheus
    depends_on:
      - kafka-jmx-exporter
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD : kafka
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
    volumes:
     - ./grafana/provisioning:/etc/grafana/provisioning
     - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
     - prometheus
  
  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: renderer
    ports:
      - 8081:8081
    depends_on:
     - grafana

networks:
  default: 
    external: 
      name: kafka-network
