data_path : 'data/$timestamp$/'

monitoring:
  docker : 'monitoring/docker-monitor/logs'
  prometheus : 'monitoring/prometheus'

message-database:
  enabled : True
  url : mongodb://admin:kafka@localhost:27017/
  database : MESSAGES
  table : MESSAGES_RECIEVED

database-scheduler:
  enabled : True
  host : localhost
  user : root
  password : kafka
  database : MESSAGES
  table : MESSAGES_RECIEVED