version: '3'

services:
  performance:
    build: ./performance
    container_name: performance
    image: abianik/ms_performance
    volumes:
      - ./..:/app
    environment:
      - EXPERIMENT_DURATION_HOURS=${EXPERIMENT_DURATION_HOURS:-0.1}
      - EXPERIMENT_MESSAGE_COUNT=${EXPERIMENT_MESSAGE_COUNT:-10000}
      - DATABASE_SCHEDULER_ENABLED=${DATABASE_SCHEDULER_ENABLED:-True}
      - MESSAGE_DATABASE_ENABLED=${MESSAGE_DATABASE_ENABLED:-True}

networks:
  default:
    external:
      name: kafka-network