version: '3'

services:
  performance:
    build: ./performance
    container_name: performance
    image: abianik/ms_performance
    volumes:
      - ./..:/app
    environment:
      - EXPERIMENT_DURATION_HOURS=${EXPERIMENT_DURATION_HOURS:-0.1}
      - EXPERIMENT_MESSAGE_COUNT=${EXPERIMENT_MESSAGE_COUNT:-10000}
      - KAFKA_ENABLED=${KAFKA_ENABLED:-True}
      - MESSENGER_DATABASE_URL=${MESSENGER_DATABASE_URL:-mongodb://admin:kafka@mongo:27017/}
      - DATABASE_SCHEDULER_CASSANDRA_ENABLED=${DATABASE_SCHEDULER_CASSANDRA_ENABLED:-True}
      - DATABASE_SCHEDULER_CASSANDRA_HOST=cassandra
      - DATABASE_SCHEDULER_MYSQL_ENABLED=${DATABASE_SCHEDULER_MYSQL_ENABLED:-True}
      - DATABASE_SCHEDULER_MYSQL_HOST=mysql
networks:
  default:
    external:
      name: kafka-network