version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_ALL:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_INT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_ALL://192.168.1.4:9092,PLAINTEXT://:19092,PLAINTEXT_INT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
    restart: unless-stopped
  
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
  
  kafka-exporter:
    image: "sscaling/jmx-prometheus-exporter"
    container_name: kafka-exporter
    ports:
     - "5556:5556"
    environment:
     CONFIG_YML : "/etc/jmx_exporter/config.yml"
    volumes:
     - ./kafka/config.yml:/etc/jmx_exporter/config.yml
    depends_on:
     - kafka
  
  prometheus:
    image: "prom/prometheus:latest"
    container_name: prometheus
    ports:
     - 9090:9090
    volumes:
     - ./kafka/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - kafka-exporter
  
  grafana:
    image: "grafana/grafana:latest"
    container_name: grafana
    ports:
     - 3000:3000
    environment:
      GF_PATHS_DATA : /var/lib/grafana
      GF_SECURITY_ADMIN_PASSWORD : kafka
    volumes:
     - ./grafana/provisioning:/etc/grafana/provisioning
     - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
     - prometheus